export const LOAD_BROCHURES = 'LOAD_BROCHURES'
export const LOAD_BROCHURES_COUNT = 'LOAD_BROCHURES_COUNT'
export const LOAD_TRASHES = 'LOAD_TRASHES'
export const LOAD_TRASHES_COUNT = 'LOAD_TRASHES_COUNT'
